application: defeo-lu-services
version: 1-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: yaml
  version: latest
